image: node:18
definitions:
    steps:
        - step: &Installation
              name: Installation
              caches:
                  - node
              script:
                  - npm install
                  - npm run build
              artifacts:
                  - node_modules/** # Save modules for next steps
                  - dist/**
        - step: &dev_deploy
              name: Deploy
              deployment: dev
              script:
                  - apt-get update -y
                  - apt-get install -y rsync
                  - ssh -o StrictHostKeyChecking=no -p 2289 $SSH_USERNAME@asterdev.ultatel.com 'rm -rf /root/dist/ /root/node_modules/'
                  - rsync -a ./dist ./node_modules -e "ssh -o StrictHostKeyChecking=no -p 2289" $SSH_USERNAME@asterdev.ultatel.com:/root/
                  - ssh -o StrictHostKeyChecking=no -p 2289 $SSH_USERNAME@asterdev.ultatel.com '/root/deploy.sh'

        - step: &test_deploy
              name: Deploy
              deployment: test
              script:
                  - apt-get update -y
                  - apt-get install -y rsync
                  - tar -cvf newdeploy.tar dist node_modules
                  - rsync -a newdeploy.tar -e "ssh -o StrictHostKeyChecking=no -p 2289" $SSH_USERNAME@38.91.52.85:/root/
                  - rsync -a newdeploy.tar -e "ssh -o StrictHostKeyChecking=no -p 2289" $SSH_USERNAME@38.91.52.90:/root/
                  - rsync -a newdeploy.tar -e "ssh -o StrictHostKeyChecking=no -p 2289" $SSH_USERNAME@38.91.52.91:/root/
                  - ssh -o StrictHostKeyChecking=no -p 2289 $SSH_USERNAME@38.91.52.85 '/root/deploy.sh'
                  - ssh -o StrictHostKeyChecking=no -p 2289 $SSH_USERNAME@38.91.52.90 '/root/deploy.sh'
                  - ssh -o StrictHostKeyChecking=no -p 2289 $SSH_USERNAME@38.91.52.91 '/root/deploy.sh'

pipelines:
    branches:
        dev:
            - step: *Installation
            - step: *dev_deploy

        test:
            - step: *Installation
            - step: *test_deploy
