name: main

# Controls when the action will run.
on:
    # Triggers the workflow on push events to the main branch.
    push:
        branches: [main]
    pull_request:
        branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
    # This workflow contains a single job called "deploy"
    build:
        # The type of runner that the job will run on
        runs-on: self-hosted

        # Steps represent a sequence of tasks that will be executed as part of the job.
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm i
            - run: npm run build
            - run: cp -r  /var/www/action-runner-api/Api/Chehabi.Academy.API/Chehabi.Academy.API/dist/* /root/user/chehabi-academy_api/
            - run: sudo pm2 stop 0
            - run: cd /usr/local/chehabi_academy_api/
            - run: sudo pm2 start main.js
            - run: sudo pm2 save
            - run: sudo service nginx restart
