export enum ErrorCodesEnum {
	USER_NOT_FOUND = 'USER_NOT_FOUND',
	USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
	WRONG_PASSWORD = 'WRONG_PASSWORD',
	FALSE_GOOGLE_LOGIN = 'FALSE_GOOGLE_LOGIN',
	INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR'
}
