export enum ErrorCodesEnum {
	USER_NOT_FOUND = 'USER_NOT_FOUND',
	USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
	WRONG_PASSWORD = 'WRONG_PASSWORD',
	FALSE_GOOGLE_LOGIN = 'FALSE_GOOGLE_LOGIN',
	MAX_CLASS_USERS = 'MAX_CLASS_USERS',
	USER_EXISTS_CLASS = 'USER_EXISTS_CLASS',
	USER_EXISTS_COURSE = 'USER_EXISTS_COURSE'
}
