export enum ErrorCodesEnum {
	USER_NOT_FOUND = 'USER_NOT_FOUND',
	USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
	WRONG_PASSWORD = 'WRONG_PASSWORD',
	PASSWORD_NOT_MATCH = 'PASSWORD_NOT_MATCH',
	FALSE_GOOGLE_LOGIN = 'FALSE_GOOGLE_LOGIN',
	MAX_CLASS_USERS = 'MAX_CLASS_USERS',
	USER_EXISTS_CLASS = 'USER_EXISTS_CLASS',
	USER_EXISTS_COURSE = 'USER_EXISTS_COURSE',
	COURSE_STARTDATE_EXCEEDED = 'COURSE_STARTDATE_EXCEEDED',
	COURSE_STARTDATE_BEFORE_TODAY = 'COURSE_STARTDATE_BEFORE_TODAY',
	COURSE_NOT_FOUND = 'COURSE_NOT_FOUND',

	Class_STARTDATE_BEFORE_TODAY = 'Class_STARTDATE_BEFORE_TODAY',
	CLASS_BEFORE_COURSE = 'CLASS_BEFORE_COURSE',
	SESSION_BEFORE_CLASS = 'SESSION_BEFORE_CLASS',
	STRIPE_WEBHOOK_ERROR = 'STRIPE_WEBHOOK_ERROR',
	CLASS_INACTIVE = 'CLASS_INACTIVE',
	CLASS_DELETED = 'CLASS_DELETED',
	CLASS_Started = 'CLASS_Started',
	CLASS_HAS_NO_FREETRIAL = 'CLASS_HAS_NO_FREETRIAL',

	//Notification template error
	EMAIL_NOT_Sent = 'Email not sent:',
	Invalid_Notification_Type = 'Invalid notification type',
	Template_Not_Found = 'Template not found',
	USER_NOT_CREATOR = 'USER_NOT_CREATOR',
	USER_NOT_ADMIN = 'USER_NOT_ADMIN'
}
